import os
import subprocess
from flask import Flask, request, jsonify
from playwright.sync_api import sync_playwright
from huggingface_hub import HfApi

app = Flask(__name__)

# --- CONFIGURATION (Set these in Koyeb Envs) ---
HF_TOKEN = os.getenv("HF_TOKEN")
REPO_ID = os.getenv("REPO_ID") # e.g., "your-username/your-repo"
HF_API = HfApi()

def generate_cookies():
    """Generates a Netscape cookies.txt using your extension's logic."""
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.new_context()
        page = context.new_page()
        page.goto("https://www.youtube.com") # Priming the session
        
        raw_cookies = context.cookies()
        lines = ["# Netscape HTTP Cookie File", "# Generated by Gemini Custom Downloader", ""]

        for c in raw_cookies:
            domain = c['domain']
            flag = "TRUE" if domain.startswith('.') else "FALSE"
            path = c['path']
            secure = "TRUE" if c['secure'] else "FALSE"
            expiry = str(int(c.get('expires', 0)))
            lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{c['name']}\t{c['value']}")

        with open("cookies.txt", "w") as f:
            f.write("\n".join(lines))
        browser.close()

@app.route('/api/process-link', methods=['POST'])
def process_link():
    url = request.json.get('url')
    video_id = url.split("v=")[-1]
    output_file = f"{video_id}.mp4"

    try:
        # 1. Export fresh cookies
        generate_cookies()

        # 2. Download with Moov Atom Fix (FastStart)
        # This fixes the 'fatal error' by moving metadata to the front
        cmd = [
            "yt-dlp", "--cookies", "cookies.txt",
            "-f", "bestvideo+bestaudio/best",
            "--merge-output-format", "mp4",
            "-o", "temp_video.mp4",
            "--exec", f"ffmpeg -i temp_video.mp4 -c copy -movflags +faststart {output_file} && rm temp_video.mp4",
            url
        ]
        subprocess.run(cmd, check=True)

        # 3. Upload to Hugging Face Hub
        HF_API.upload_file(
            path_or_fileobj=output_file,
            path_in_repo=f"downloads/{output_file}",
            repo_id=REPO_ID,
            token=HF_TOKEN
        )

        return jsonify({"status": "success", "file": output_file})
    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8080)
