import subprocess
import os
import sys

def download_video(video_url):
    # This path is where exporter.py saves the fresh session
    cookie_file = "cookies.txt"
    
    if not os.path.exists(cookie_file):
        print("❌ Error: cookies.txt not found. Run exporter.py first!")
        return

    print(f"🚀 Starting download for: {video_url}")

    # Use the Netscape cookies generated by your extension logic
    command = [
        "yt-dlp",
        "--cookies", cookie_file,
        "-f", "bestvideo+bestaudio/best",
        "--merge-output-format", "mp4",
        # Ensures the video is playable immediately (fixes 'moov atom' issues)
        "--exec", "ffmpeg -i {} -c copy -movflags +faststart {}.fixed.mp4 && rm {}",
        video_url
    ]

    try:
        subprocess.run(command, check=True)
        print("✅ Download completed successfully!")
    except subprocess.CalledProcessError as e:
        print(f"❌ Download failed: {e}")

if __name__ == "__main__":
    # Check if a URL was passed from the command line
    if len(sys.argv) > 1:
        url = sys.argv[1]
        download_video(url)
    else:
        print("⚠️ Usage: python your_main_downloader.py <YOUTUBE_URL>")
